/*------------------------------------------------------------------------------------------------------/
| Program : FAB:~!~!~!~.js
| Event   : FeeAssessBefore
|
| Client  : Placer County, CA
| Usage   : 
| 
|
| Requires: EMSE 3.0 and Standard Choice: "EMSE_EXECUTE_OPTIONS": "SCRIPT" to be Active.
|
| Notes   : TDunn 01/02/2024 created script.
|		  : TDunn 01/03/2024 added logic preventing the addition of fees to Pre-Application records.
|
|
/---------------------------------------------------------------------------------------------------------------------*/

if(matches(currentUserID == "TDUNN","EAFTAHI","JMCKENZIE"))
{
	showDebug = 1;
}
// Start of variable declaration
//===================================
var thisAmt = 0;

// Begin rules for Planning record types
//--------------------------------------
if(matches(appTypeArray[1],"Pre-Application"))
{
    showMessage = true;
    customComment("Fees are not allowed on Planning Pre-Applications. Any fees applicable to the Planning project to be generated by this pre-application will/should be applied directly to that project.");
    cancel = true;
}